# Generated by Django 5.2.4 on 2025-07-28 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stckmain',
            name='created_by',
            field=models.CharField(default='admin', max_length=100),
        ),
        migrations.AddField(
            model_name='stckmain',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stckmain',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='prodmast',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stckdetail',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='inventory.stckmain'),
        ),
    ]
